import type { ZodTypeAny } from 'zod';
import {
  heroSlideInput,
  heroSlideUpdate,
  pageInput,
  pageUpdate,
  serviceInput,
  serviceUpdate,
  methodologyPillarInput,
  methodologyPillarUpdate,
  statisticInput,
  statisticUpdate,
  partnerInput,
  partnerUpdate,
  teamMemberInput,
  teamMemberUpdate,
  timelineEntryInput,
  timelineEntryUpdate,
  eventInput,
  eventUpdate,
  faqInput,
  faqUpdate,
  countryInput,
  countryUpdate,
  newsArticleInput,
  newsArticleUpdate,
  testimonialInput,
  testimonialUpdate,
  announcementInput,
  announcementUpdate,
  popupInput,
  popupUpdate,
  availabilitySlotInput,
  availabilitySlotUpdate,
} from '@ala/types';

export interface ResourceConfig {
  /** URL segment, e.g. "hero-slides" */
  path: string;
  /** Postgres table name */
  table: string;
  createSchema: ZodTypeAny;
  updateSchema: ZodTypeAny;
  /** Exposed on the public GET API? */
  publicRead: boolean;
  /** Table has an is_published column (public reads filter on it). */
  hasPublished: boolean;
  /** Table has a slug column → enable GET /:slug. */
  hasSlug: boolean;
  /** Supports PATCH /reorder. */
  orderable: boolean;
  /** Columns searched by the admin list ?search= param. */
  searchColumns: string[];
  /** Default ordering for list responses. */
  defaultSort: string;
  defaultOrder: 'asc' | 'desc';
}

export const resources: Record<string, ResourceConfig> = {
  'hero-slides': {
    path: 'hero-slides',
    table: 'hero_slides',
    createSchema: heroSlideInput,
    updateSchema: heroSlideUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: false,
    orderable: true,
    searchColumns: ['title_en', 'title_fr'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  pages: {
    path: 'pages',
    table: 'pages',
    createSchema: pageInput,
    updateSchema: pageUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: true,
    orderable: false,
    searchColumns: ['title_en', 'slug'],
    defaultSort: 'title_en',
    defaultOrder: 'asc',
  },
  services: {
    path: 'services',
    table: 'services',
    createSchema: serviceInput,
    updateSchema: serviceUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: true,
    orderable: true,
    searchColumns: ['title_en', 'title_fr', 'slug'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  methodology: {
    path: 'methodology',
    table: 'methodology_pillars',
    createSchema: methodologyPillarInput,
    updateSchema: methodologyPillarUpdate,
    publicRead: true,
    hasPublished: false,
    hasSlug: false,
    orderable: true,
    searchColumns: ['title_en'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  statistics: {
    path: 'statistics',
    table: 'statistics',
    createSchema: statisticInput,
    updateSchema: statisticUpdate,
    publicRead: true,
    hasPublished: false,
    hasSlug: false,
    orderable: true,
    searchColumns: ['label_en'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  partners: {
    path: 'partners',
    table: 'partners',
    createSchema: partnerInput,
    updateSchema: partnerUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: false,
    orderable: true,
    searchColumns: ['name'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  team: {
    path: 'team',
    table: 'team_members',
    createSchema: teamMemberInput,
    updateSchema: teamMemberUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: false,
    orderable: true,
    searchColumns: ['full_name', 'role_en'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  timeline: {
    path: 'timeline',
    table: 'timeline_entries',
    createSchema: timelineEntryInput,
    updateSchema: timelineEntryUpdate,
    publicRead: true,
    hasPublished: false,
    hasSlug: false,
    orderable: true,
    searchColumns: ['title_en', 'year'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  faqs: {
    path: 'faqs',
    table: 'faqs',
    createSchema: faqInput,
    updateSchema: faqUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: false,
    orderable: true,
    searchColumns: ['question_en'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  // Events are registered here for admin CRUD, but also have a dedicated
  // router (gallery sub-resource + upcoming/past filters).
  events: {
    path: 'events',
    table: 'events',
    createSchema: eventInput,
    updateSchema: eventUpdate,
    publicRead: false, // served by the dedicated events router instead
    hasPublished: true,
    hasSlug: true,
    orderable: false,
    searchColumns: ['title_en', 'location', 'slug'],
    defaultSort: 'start_date',
    defaultOrder: 'desc',
  },
  countries: {
    path: 'countries',
    table: 'countries',
    createSchema: countryInput,
    updateSchema: countryUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: true,
    orderable: true,
    searchColumns: ['name_en', 'name_fr', 'slug'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  news: {
    path: 'news',
    table: 'news_articles',
    createSchema: newsArticleInput,
    updateSchema: newsArticleUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: true,
    orderable: false,
    searchColumns: ['title_en', 'title_fr', 'slug', 'category'],
    defaultSort: 'published_at',
    defaultOrder: 'desc',
  },
  testimonials: {
    path: 'testimonials',
    table: 'testimonials',
    createSchema: testimonialInput,
    updateSchema: testimonialUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: false,
    orderable: true,
    searchColumns: ['author_name', 'country'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  announcements: {
    path: 'announcements',
    table: 'announcements',
    createSchema: announcementInput,
    updateSchema: announcementUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: false,
    orderable: true,
    searchColumns: ['message_en'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  popups: {
    path: 'popups',
    table: 'popups',
    createSchema: popupInput,
    updateSchema: popupUpdate,
    publicRead: true,
    hasPublished: true,
    hasSlug: false,
    orderable: true,
    searchColumns: ['name'],
    defaultSort: 'sort_order',
    defaultOrder: 'asc',
  },
  'availability-slots': {
    path: 'availability-slots',
    table: 'availability_slots',
    createSchema: availabilitySlotInput,
    updateSchema: availabilitySlotUpdate,
    publicRead: false, // clients read open slots via the portal endpoint
    hasPublished: false,
    hasSlug: false,
    orderable: false,
    searchColumns: [],
    defaultSort: 'starts_at',
    defaultOrder: 'asc',
  },
};
