import {
  Briefcase,
  TrendingUp,
  LineChart,
  BarChart3,
  Globe,
  Globe2,
  Plane,
  Ship,
  Truck,
  Handshake,
  Users,
  UserCheck,
  Building2,
  Landmark,
  Scale,
  Gavel,
  FileText,
  FileCheck,
  Stamp,
  BadgeCheck,
  Award,
  Target,
  Lightbulb,
  Rocket,
  Compass,
  Map,
  MapPin,
  Calendar,
  CalendarCheck,
  Ticket,
  Presentation,
  Coins,
  Banknote,
  DollarSign,
  PiggyBank,
  Wallet,
  ShieldCheck,
  Network,
  Layers,
  Package,
  ClipboardCheck,
  Megaphone,
  Star,
  Bot,
  Cpu,
  GraduationCap,
  BookOpen,
  type LucideIcon,
} from 'lucide-react';

/**
 * Curated Lucide set for services (icon_name). Statically imported so only
 * these icons are bundled. The admin icon picker offers exactly these keys.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  'trending-up': TrendingUp,
  'line-chart': LineChart,
  'bar-chart': BarChart3,
  globe: Globe,
  'globe-2': Globe2,
  plane: Plane,
  ship: Ship,
  truck: Truck,
  handshake: Handshake,
  users: Users,
  'user-check': UserCheck,
  building: Building2,
  landmark: Landmark,
  scale: Scale,
  gavel: Gavel,
  'file-text': FileText,
  'file-check': FileCheck,
  stamp: Stamp,
  'badge-check': BadgeCheck,
  award: Award,
  target: Target,
  lightbulb: Lightbulb,
  rocket: Rocket,
  compass: Compass,
  map: Map,
  'map-pin': MapPin,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  ticket: Ticket,
  presentation: Presentation,
  coins: Coins,
  banknote: Banknote,
  'dollar-sign': DollarSign,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  'shield-check': ShieldCheck,
  network: Network,
  layers: Layers,
  package: Package,
  'clipboard-check': ClipboardCheck,
  megaphone: Megaphone,
  star: Star,
  bot: Bot,
  cpu: Cpu,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
};

export const ICON_NAMES = Object.keys(ICON_REGISTRY);

export function normalizeIconName(name?: string | null): string {
  if (!name) return '';
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}
